### ISSUE TITLE
GetTweetsFromUserIdAsync ends up putting multiple expansion fields in the url

### ISSUE THREAD

**Issue by Foxite** [Xwilarg/TwitterSharp#2]
A line such as this:

```
await twitter.GetTweetsFromUserIdAsync(
	user.Id,
	new[] { TweetOption.Source, TweetOption.Attachments, TweetOption.Entities, TweetOption.Created_At, TweetOption.In_Reply_To_User_Id },
	Array.Empty<UserOption>(),
	Array.Empty<MediaOption>()
)
```

Results in a HTTP 400 because the URL becomes this:

`https://api.twitter.com/2/users/.../tweets?expansions=attachments.media_keys&tweet.fields=source,attachments,entities,created_at,in_reply_to_user_id&expansions=author_id`

Note how it has both `?expansions=attachment.media_keys` and `&expansions=author_id`.

[AddTweetOptions](https://github.com/Xwilarg/TwitterSharp/blob/master/TwitterSharp/Client/TwitterClient.cs#L193) adds author_id to the expansions if TweetOptions.Attachments is specified. [AddUserOptions](https://github.com/Xwilarg/TwitterSharp/blob/master/TwitterSharp/Client/TwitterClient.cs#L173) always adds author_id, but it doesn't check if expansions are already specified (and to its defense, this is pretty hard in the current code).

Proposed solution: Instead of passing around the full URL string with the query, pass around a Dictionary<string, string> and fill it with parameters, and then turn it into a query string before executing the request. If AddUserOptions sees that `expansions` is already in the dictionary, it will append `,author_id` to the value instead of setting it to `author_id`.

**Comment by Xwilarg** [comment]
I'll look at that, thanks!

**Comment by Xwilarg** [comment]
This should be fixed with 9a4eb605dd73ae71126d424834a0398bebf77532

**Comment by Xwilarg** [comment]
Closing the issue since this is fixed, feel free to reopen it again if needed

**Comment by Foxite** [comment]
I was writing a response describing a new problem, but I think it would be better if I made that a separate issue anyway :upside_down_face:

**Comment by Xwilarg** [comment]
Ah yup, I'll be waiting for your new issue then!

**Comment by Xwilarg** [comment]
(Oops referenced wrong issue)
