### ISSUE TITLE
HasMedia and HasImages

### ISSUE THREAD

**Issue by rob-mur** [Xwilarg/TwitterSharp#21]
Hi

I may just be being dumb, but whenever I use HasMedia or HasImages in AddTweetStreamAsync, it doesn't actually add the rules to the stream. In particular, the StreamInfo[] it returns is empty, and any future call to NextTweetStreamAsync fails.

For now I'll just ignore it and manually filter it but would be cleaner if this functionality was working. Shout if there's more information you need to replicate.

**Comment by Xwilarg** [comment]
I'll check that
If you could provide a small example to reproduce the issue that would be nice tho :)

**Comment by rob-mur** [comment]
Hi

Upon re-creating a simple console application to highlight the bug, I have been unable to reproduce it (as is always the way).

For future reference, I saw this error in a Blazor Server-Side App, whilst in a relatively low connectivity environment (poor internet whilst travelling), and potentially that had something to do with it.

Given I can't re-produce it deterministically now though I'm happy for this to be closed.
