### ISSUE TITLE
GetTweetsFromUserIdAsync `since_id` parameter

### ISSUE THREAD

**Issue by jvyden** [Xwilarg/TwitterSharp#22]
I'm building a bot that fetches the latest tweet from a brand account's twitter page. I expected to be able to use the `since_id` parameter, documented [here](https://developer.twitter.com/en/docs/twitter-api/tweets/timelines/api-reference/get-users-id-tweets), but I did not find any way to use it.

Is this unimplemented or am I just not finding it anywhere?

**Comment by Xwilarg** [comment]
Hey it's me again, this should be implemented with the version [2.1.0](https://www.nuget.org/packages/TwitterSharp/2.1.0), please tell me if it works fine for you

Here is an example on how to use it:
```cs
var answer = await client.GetTweetsFromUserIdAsync("1200397238788247552", new TweetSearchOptions
{
    StartTime = new DateTime(2021, 7, 1, 12, 50, 0)
});
```

**Comment by jvyden** [comment]
Seems to work as expected. Thanks for implementing this!

**Comment by Xwilarg** [comment]
Small footnote, I just realized I showed the wrong example but here is the one for since_id, just in case:
```cs
var client = new TwitterClient(Environment.GetEnvironmentVariable("TWITTER_TOKEN"));
            var answer = await client.GetTweetsFromUserIdAsync("1200397238788247552", new TweetSearchOptions
            {
                SinceId = "1410551383795781634"
            });
