### ISSUE TITLE
How can I get the last new Tweets from subscribed users without or as background task

### ISSUE THREAD

**Issue by AlexGer123** [Xwilarg/TwitterSharp#7]
Hi again... :),

I want to get the last tweets from subscribed users without any background task. (I try IHostedService... but I dont get it... :/ )

It is possible to subscrib some users and then calling methode like NextTweetStreamAsync to get all the last tweets since last calling NextTweetStreamAsync? So I can decides when I want to get the last Tweets.

If I use
```cs
 var t = Task.Run(async () =>
 {
     // Take in parameter a callback called for each new tweet
     // Since we want to get the basic info of the tweet author, we add an empty array of UserOption
     await client.NextTweetStreamAsync((tweet) =>
      {
          Console.WriteLine($"From {tweet.Author.Name}: {tweet.Text}");
      }, null, Array.Empty<UserOption>());
 });
t.Wait();
```
it will catch all tweets well but I can not do anything else. Someone have a good IHostedService / BackgroundService example?

**Comment by Xwilarg** [comment]
To get the latest tweets of an user you can use GetTweetsFromUserIdAsync

About your code sample, if you remove the t.Wait() it'll still do the things in background and you'll be able to do others things at the same time

**Comment by AlexGer123** [comment]
You are right! 👍 
Sometimes some little thing is missing. Thank you!

```cs
var client = new TwitterSharp.Client.TwitterClient(bearer_token);

var t = Task.Run(async () =>
{
    // Take in parameter a callback called for each new tweet
    // Since we want to get the basic info of the tweet author, we add an empty array of UserOption
    await client.NextTweetStreamAsync((tweet) =>
    {
        Console.WriteLine($"From {tweet.Author.Name}: {tweet.Text}");
    }, null, Array.Empty<UserOption>());
});

while (true)
{
    Console.WriteLine("Other task");
    Thread.Sleep(1000);
}
```
![image](https://user-images.githubusercontent.com/8454972/145705235-a61dc7b2-b756-4bf9-bcde-cf90d3bb0227.png)
